services:
  postgres:
    image: postgres:17-alpine
    container_name: probase-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: probase
      POSTGRES_PASSWORD: probase123
      POSTGRES_DB: probase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
