// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Prisma 7 generates its client as .ts source whose internal imports carry
    // .js extensions, which ts-node's CJS resolver will not map back — so the
    // seed runs from compiled output rather than through ts-node.
    seed: 'nest build && node dist/prisma/seed.js',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
